-- Bug crítico ao vivo: existem DUAS versões de public.apply_order_drop no
-- banco --
--
--   1) apply_order_drop(uuid, text, uuid, text) -- a versão correta, a que
--      resolve_drop_request() e admin_drop_order() de fato chamam hoje.
--   2) apply_order_drop(uuid, text, uuid, text, text default
--      'awaiting_assignment') -- sobra de um sistema de advertência de
--      booster (penalty_bucket/heavy_loss/light_loss, warning_issued,
--      blocked_until, auto-suspensão em 5 advertências) que foi abandonado
--      -- referencia order_drop_requests.penalty_bucket, .waived_at e
--      .warning_issued, colunas que NUNCA existiram nesta tabela. Nunca
--      funcionou de verdade.
--
-- CREATE OR REPLACE não troca uma função por outra quando a assinatura de
-- parâmetros muda -- cria um overload novo. Como o 5º parâmetro da versão
-- órfã tem DEFAULT, ela também "aceita" ser chamada com só 4 argumentos --
-- exatamente como resolve_drop_request()/admin_drop_order() chamam. Postgres
-- não consegue decidir entre as duas (os 4 primeiros tipos são idênticos) e
-- toda chamada explode com "function apply_order_drop(uuid, text, uuid,
-- text) is not unique". Isso quebra TODO o fluxo de drop pra qualquer ator:
-- o pedido de drop em si (request_order_drop/request_customer_order_drop)
-- não chama apply_order_drop e continua funcionando -- mas fica pra sempre
-- travado em 'drop_requested', porque tanto a aprovação do admin
-- (resolve_drop_request) quanto o drop direto do admin (admin_drop_order)
-- chamam a função ambígua e falham sempre.
--
-- Fix: remove a sobra órfã. A versão correta (4 params) continua intacta e
-- passa a ser a única candidata de novo.
drop function if exists public.apply_order_drop(uuid, text, uuid, text, text);
