-- profiles.username agora vem só do Discord (name/full_name na candidatura,
-- ver 20260814060000_fix_discord_username_discriminator.sql) e não deve
-- poder ser trocado pelo usuário nunca -- só o display_name do booster tem
-- essa liberdade (com cooldown de 30 dias via update_my_display_name).
-- UserProfilePanel.tsx removeu o campo de edição de username, mas a RPC
-- update_my_username (SECURITY DEFINER) continuava chamável direto contra a
-- API do Supabase, contornando trg_fn_guard_profiles_trust_columns (que só
-- bloqueia UPDATE direto de authenticated não-admin -- RPCs SECURITY DEFINER
-- rodam como o dono da função, então o guard não pega). Revoga o execute em
-- vez de dropar a function, pra manter a rota disponível só a service_role
-- (scripts administrativos), sem quebrar nada que dependa dela existir.
revoke execute on function public.update_my_username(text) from authenticated;
